env:
    rclone_config: "ENCRYPTED[258406cd70f27dc298893934a7a10dcbb98d879ac3bb51b6c5e53b8659815a865cd2b00b588d4b65a0aa3ce346c21309]"
    TG_TOKEN: "ENCRYPTED[7888fd688129c58fcd9a25086dad02a0c103986cfca92f0d1606b3873ab2e02fffacffe4a8a432b0d726eff81999323e]"
    TG_CHAT_ID: "ENCRYPTED[e06537f430d3e1dfd6bd23c324f9f5d0ac0a67807e496b194aa1a1bfb4c4a8aae6b6eb77bdcb5ae2f043b9b09cc00bc5]"
    SF_USERNAME: "ENCRYPTED[9b9deac88b090b7dc4e69a058e79360e8832c782b9bd46499a7f1401e66e219bad7c9c901a85eeb0d154f717cfc5f148]"
    SF_PASS: "ENCRYPTED[9d4e6509f1294d4d9b39c9f092f32123bef7cdf2c773cda6f80867a329c629d6ab9f1cee0db0c38184bd13d8e8a5556f]"
    GIT: "ENCRYPTED[293e9962b531796f7d2c267cb481cbb126e69405c451abeb85e1645fe29f7d32c6cb22c2a7b6d186c347aefd666d3e3b]"
    ROM_PROJECT: "cherish-12.1"
 
task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 1h  
  container:
      image: inok2341/anu:latest
      cpu: 2
      memory: 8G

  Download_script:
      - cd ~
      #- git config --global user.name "ariffjenong"
      #- git config --global user.email "arifbuditantodablekk@gmail.com"
      #- echo "$GIT" > ~/.git-credentials
      #- git config --global credential.helper store --file=~/.git-credentials
      - mkdir -p ~/.config/rclone
      - echo "$rclone_config" > ~/.config/rclone/rclone.conf
      - mkdir -p ~/rom/out/target/product/maple
      - cd ~/rom/out/target/product/maple
      - time aria2c https://roms.cirrus-ci.workers.dev/0:/maple/Cherish-OS-v3.5.5-20220331-0404-maple-UNOFFICIAL-Vanilla.zip -x16 -s50
      #- mkdir -p ~/rom/out/target/product/maple_dsds
      #- cd ~/rom/out/target/product/maple_dsds
      #- time aria2c https://roms.cirrus-ci.workers.dev/0:/maple_dsds/Cherish-OS-v3.5.5-20220331-0112-maple_dsds-UNOFFICIAL-GApps.zip -x16 -s50
      #- time aria2c https://roms.cirrus-ci.workers.dev/0:/maple_dsds/Cherish-OS-v3.5.5-20220330-1957-maple_dsds-UNOFFICIAL-Vanilla.zip -x16 -s50

  SF_script:
      - ./sf.sh
      #- ./build_zip.sh
      - cd ~/rom/out/target/product/maple
      - time rclone copy $(ls *.zip) znxtproject:rom/$ROM_PROJECT/maple -P
      #- cd ~/rom/out/target/product/maple_dsds
      #- time rclone copy $(ls *GApps*.zip) znxtproject:rom/$ROM_PROJECT/maple_dsds -P
      #- time rclone copy $(ls *Vanilla*.zip) znxtproject:rom/$ROM_PROJECT/maple_dsds -P
      - cd ~ && rm -rf rom #&& rm .git-credentials
 