env:
    gcp_credentials: "ENCRYPTED[52d9731bab8dea7e2f71cbd5162d10dc57e1c8a9e91779b86758948763c13b48d21681a2f0f20a8e6c5133dfbb445c47]"
    rclone_config: "ENCRYPTED[3c83ff4e129f1ced7d697b973f99d3cf33fd7936b9ad27602c7ffa47c5d678da1c8cc1fcf2ab067b09fe35e501b6ad75]"
    TG_TOKEN: "ENCRYPTED[7888fd688129c58fcd9a25086dad02a0c103986cfca92f0d1606b3873ab2e02fffacffe4a8a432b0d726eff81999323e]"
    TG_CHAT_ID: "ENCRYPTED[e06537f430d3e1dfd6bd23c324f9f5d0ac0a67807e496b194aa1a1bfb4c4a8aae6b6eb77bdcb5ae2f043b9b09cc00bc5]"
    SF_USERNAME: "ENCRYPTED[9b9deac88b090b7dc4e69a058e79360e8832c782b9bd46499a7f1401e66e219bad7c9c901a85eeb0d154f717cfc5f148]"
    SF_PASS: "ENCRYPTED[9d4e6509f1294d4d9b39c9f092f32123bef7cdf2c773cda6f80867a329c629d6ab9f1cee0db0c38184bd13d8e8a5556f]"
    ROM_PROJECT: "lineage-19.1"
 
task:
  name: Syncing, Building and Uploading
  timeout_in: 4h
  container:
      image: accupara/aosp
      cpu: 8
      memory: 32G

  Env_background_script:
      - cd ~ && rm -rf $ROM_PROJECT && rm -rf znxt
      - mkdir -p ~/$ROM_PROJECT
      - mkdir -p ~/znxt
      - mkdir -p ~/.config/rclone
      - echo "$rclone_config" > ~/.config/rclone/rclone.conf
      - time rclone copy znxtproject:ccache/$ROM_PROJECT/ccache.tar.gz ~/znxt -P
      - cd ~/znxt
      - time tar xf ccache.tar.gz
      - rm ccache.tar.gz
      - ls -lh

  Download_background_script:
      #- time rclone copy znxtproject:ccache/$ROM_PROJECT/out.tar.gz ~/$ROM_PROJECT -P
      #- cd ~/$ROM_PROJECT
      #- time tar xf out.tar.gz
      #- rm -rf out.tar.gz
      - sleep 7m
      - cd ~/$ROM_PROJECT
      - ls -lh

  Sync_script:
      - cd ~/$ROM_PROJECT
      - repo init --depth=1 --no-repo-verify -u https://github.com/ariffjenong/android.git -b lineage-19.1 -g default,-mips,-darwin,-notdefault
      - git clone https://github.com/ariffjenong/local_manifest.git --depth 1 -b LOS19 .repo/local_manifests
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j24

  Build_script:
      #- ./ziper.sh
      - ./build.sh

  UploadROM_background_script:
      - cd ~/$ROM_PROJECT/out/target/product/maple_dsds
      - ls -lh
      - rclone copy $(ls *maple*UNOFFICIAL*.zip) znxtproject:rom/$ROM_PROJECT -P && rclone copy $(ls *.md5sum) znxtproject:rom/$ROM_PROJECT -P && ls -lh

  UploadCc_script:
      - ./build_zip.sh

  SF_script:
      #- ./sf.sh
      #- curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Build $(cd ~/$ROM_PROJECT/out/target/product/maple_dsds && ls *UNOFFICIAL*.zip) Uploaded Successfully!"
      - cd ~ && rm -rf $ROM_PROJECT && rm -rf znxt
 