env:
    rclone_config: "ENCRYPTED[258406cd70f27dc298893934a7a10dcbb98d879ac3bb51b6c5e53b8659815a865cd2b00b588d4b65a0aa3ce346c21309]"
    TG_TOKEN: "ENCRYPTED[7888fd688129c58fcd9a25086dad02a0c103986cfca92f0d1606b3873ab2e02fffacffe4a8a432b0d726eff81999323e]"
    TG_CHAT_ID: "ENCRYPTED[e06537f430d3e1dfd6bd23c324f9f5d0ac0a67807e496b194aa1a1bfb4c4a8aae6b6eb77bdcb5ae2f043b9b09cc00bc5]"
    SF_USERNAME: "ENCRYPTED[9b9deac88b090b7dc4e69a058e79360e8832c782b9bd46499a7f1401e66e219bad7c9c901a85eeb0d154f717cfc5f148]"
    SF_PASS: "ENCRYPTED[9d4e6509f1294d4d9b39c9f092f32123bef7cdf2c773cda6f80867a329c629d6ab9f1cee0db0c38184bd13d8e8a5556f]"
    GIT: "ENCRYPTED[293e9962b531796f7d2c267cb481cbb126e69405c451abeb85e1645fe29f7d32c6cb22c2a7b6d186c347aefd666d3e3b]"
    m: "ENCRYPTED[4a34b08f10bcabfbe0c5148ea877c7976aa0e93eccfcf64fc1d8fe06ec37fed7b80c7a14fedc9912529729b0e6363e5d]"
    ROM_PROJECT: "nusantara-12"
 
task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 1h  
  container:
      image: inok2341/anu:latest
      cpu: 4
      memory: 8G

  Download_script:
      - cd ~
      - mkdir -p ~/.config/rclone
      - echo "$rclone_config" > ~/.config/rclone/rclone.conf
      - git config --global user.name "ariffjenong"
      - git config --global user.email "arifbuditantodablekk@gmail.com"
      - echo "$GIT" > ~/.git-credentials
      - git config --global credential.helper store --file=~/.git-credentials
      - mkdir -p ~/github/vendor_maple
      - cd ~/github
      - git clone --depth=1 https://github.com/ariffjenong/android_vendor_sony_maple.git vendor_maple
      - cd ~/github/vendor_maple
      - git checkout lineage-19
      - git remote add derf https://github.com/kgvarunkanth/android_vendor_sony_maple-new.git
      - git fetch derf
      - git cherry-pick a52636c169b604f11cd0b10c0b0d3ba0fa8b3347 && rm proprietary/vendor/lib64/mediadrm/libwvdrmengine.so && rm proprietary/vendor/lib64/libwvhidl.so && rm proprietary/vendor/lib64/libsettings.so && rm proprietary/vendor/lib64/libperipheral_client.so && rm proprietary/vendor/lib/mediadrm/libwvdrmengine.so && rm proprietary/vendor/lib/libwvhidl.so && rm proprietary/vendor/lib/libsettings.so && rm proprietary/vendor/lib/libperipheral_client.so && rm proprietary/vendor/bin/pm-service && rm proprietary/vendor/bin/pm-proxy && rm proprietary/vendor/bin/energy-awareness && rm proprietary/vendor/app/TimeService/TimeService.apk && rm proprietary/product/priv-app/qcrilmsgtunnel/qcrilmsgtunnel.apk && rm proprietary/product/priv-app/ims/ims.apk && rm proprietary/product/framework/qcrilhook.jar && rm proprietary/product/app/embms/embms.apk && rm proprietary/product/app/datastatusnotification/datastatusnotification.apk && rm proprietary/product/app/QtiTelephonyService/QtiTelephonyService.apk && rm proprietary/framework/com.fingerprints.extension.jar
      - git add . && git commit
      - git push origin lineage-19.0
      - git checkout cherish-12
      - git remote add derf https://github.com/kgvarunkanth/android_vendor_sony_maple-new.git
      - git fetch derf
      - git cherry-pick a52636c169b604f11cd0b10c0b0d3ba0fa8b3347 && rm proprietary/vendor/lib64/mediadrm/libwvdrmengine.so && rm proprietary/vendor/lib64/libwvhidl.so && rm proprietary/vendor/lib64/libsettings.so && rm proprietary/vendor/lib64/libperipheral_client.so && rm proprietary/vendor/lib/mediadrm/libwvdrmengine.so && rm proprietary/vendor/lib/libwvhidl.so && rm proprietary/vendor/lib/libsettings.so && rm proprietary/vendor/lib/libperipheral_client.so && rm proprietary/vendor/bin/pm-service && rm proprietary/vendor/bin/pm-proxy && rm proprietary/vendor/bin/energy-awareness && rm proprietary/vendor/app/TimeService/TimeService.apk && rm proprietary/product/priv-app/qcrilmsgtunnel/qcrilmsgtunnel.apk && rm proprietary/product/priv-app/ims/ims.apk && rm proprietary/product/framework/qcrilhook.jar && rm proprietary/product/app/embms/embms.apk && rm proprietary/product/app/datastatusnotification/datastatusnotification.apk && rm proprietary/product/app/QtiTelephonyService/QtiTelephonyService.apk && rm proprietary/framework/com.fingerprints.extension.jar
      - git add . && git commit
      - git push origin cherish-12

  SF_script:
      - cd ~ && rm -rf .config && rm -rf github && rm .git-credentials

 