env:
    rcloneconfig: "ENCRYPTED[32b6ff68080e9be8c9324bc134955912eb5b784a3eb285433315c42a66be5afe1759c3eb1e182c32db213d86025bc58a]"
    TG_TOKEN: "ENCRYPTED[7888fd688129c58fcd9a25086dad02a0c103986cfca92f0d1606b3873ab2e02fffacffe4a8a432b0d726eff81999323e]"
    TG_CHAT_ID: "ENCRYPTED[e06537f430d3e1dfd6bd23c324f9f5d0ac0a67807e496b194aa1a1bfb4c4a8aae6b6eb77bdcb5ae2f043b9b09cc00bc5]"
    LUNCH: bliss_maple_dsds-userdebug
    MAKE: bacon
 
task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m  
  container:
      image: ghcr.io/iamshubh69/docker:main
      cpu: 8
      memory: 32G
 
  Sync_script:
      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Build baru terdeteksi!"
      - echo "============================"
      - echo "Menyinkronkan Sumber..."
      - echo "============================"
      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Mulai sinkronisasi Sumber..."
      - cd ~
      - mkdir rom
      - cd rom
      - repo init --depth=1 --no-repo-verify -u https://github.com/BlissRoms/platform_manifest.git -b arcadia -g default,-mips,-darwin,-notdefault
      - git clone --depth=1 https://github.com/ariffjenong/local_manifest.git -b Bliss .repo/local_manifests
      - repo sync -c --force-sync --no-tags --no-clone-bundle -j$(nproc --all) --optimized-fetch --prune -j8

  Build_script:
      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Sinkronisasi Selesai!"
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Mulai Membangun Project"
      - export ALLOW_MISSING_DEPENDENCIES=true
      - export SELINUX_IGNORE_NEVERALLOW=true
      - export CC=clang
      - export CLANG_TRIPLE=aarch64-linux-gnu-
      - export CROSS_COMPILE=aarch64-linux-gnu-
      - export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
      - DEBIAN_FRONTEND=noninteractive
      - cd ~
      - cd rom
      - export USE_CCACHE=1 >> ~/.bashrc
      - ccache -M 40G
      - . build/envsetup.sh
      - blissify -v $LUNCH
      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Build $(cd /rom/out/target/product/maple_dsds/ && ls *.zip) Completed!"
      - echo "============================"
      - echo "Build Completed!"
      - echo "============================="

  Upload_script:
      - echo "============================"
      - echo "Mengunggah Build...."
      - echo "============================"
      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Uploading Build $(cd /rom/out/target/product/maple_dsds/ && ls *.zip)"
      - cd ~
      - cd rom
      - cd out/target/product/maple_dsds
      - ls -lh
      - pwd
      - chmod 777 *
      - curl --upload-file *.zip https://transfer.sh/$(cd /rom/out/target/product/maple_dsds/ && ls *.zip)
      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Build $(cd /rom/out/target/product/maple_dsds/ && ls *.zip) Uploaded Successfully!"
      - echo " "
      - echo "============================"
      - echo "Build Berhasil Diunggah!"
      - echo "============================"
      - echo "----------------------------"
      - cat link.txt && echo " "
      - echo "============================"
      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="$(echo "${var_cache_report_config}")"

