env:
    rcloneconfig: "ENCRYPTED[167bf9c8ad38e458c770c01052a0b9bfbf8edd8a77a8932eaa87fe9c67556261f9174eb2800a3a02541343eb9f108da4]"
    TG_TOKEN: "ENCRYPTED[7888fd688129c58fcd9a25086dad02a0c103986cfca92f0d1606b3873ab2e02fffacffe4a8a432b0d726eff81999323e]"
    TG_CHAT_ID: "ENCRYPTED[e06537f430d3e1dfd6bd23c324f9f5d0ac0a67807e496b194aa1a1bfb4c4a8aae6b6eb77bdcb5ae2f043b9b09cc00bc5]"
 
task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 4h  
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G

  Download_script:
      - url=https://roms.apon77.workers.dev/ccache/ci3/ccache.tar.gz
      - cd ~
      - mkdir -p ~/rom
      - mkdir -p ~/znxt
      - mkdir -p ~/.config/rclone
      - echo "$rcloneconfig" > ~/.config/rclone/.rclone.conf
      - cd ~/znxt
      - time aria2c $url -x16 -s50
      - time tar xf ccache.tar.gz
      - rm -rf ccache.tar.gz
      - cd ~/znxt/ccache
      - ls -lh

  Sync_script:
      - cd ~/rom
      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Build baru terdeteksi!"
      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Mulai sinkronisasi Sumber..."
      - repo init --depth=1 --no-repo-verify -u git://github.com/NusantaraProject-ROM/android_manifest.git -b 12 -g default,-mips,-darwin,-notdefault
      - git clone --depth=1 https://github.com/ariffjenong/local_manifest.git -b nad-12 .repo/local_manifests
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

  Build_script:
      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Sinkronisasi Selesai!"
      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Mulai Membangun Project"
      - cd ~
      - df -h
      - free -h
      - nproc
      - cat /etc/os*
      - env
      - cd ~/rom
      - . build/envsetup.sh
      - lunch nad_maple_dsds-userdebug
      - export CCACHE_DIR=~/znxt/ccache
      - export CCACHE_EXEC=$(which ccache)
      - export USE_CCACHE=1 >> ~/znxt/ccache/.bashrc
      - ccache -M 20G # It took only 6.4GB for mido
      - ccache -o compression=true # Will save times and data to download and upload ccache, also negligible performance issue
      - ccache -z # Clear old stats, so monitor script will provide real ccache statistics
      - export ALLOW_MISSING_DEPENDENCIES=true
      - export SELINUX_IGNORE_NEVERALLOWS=true
      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="$(echo "${var_cache_report_config}")"
      - make nad && curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Build $(cd out/target/product/maple_dsds/ && ls *.zip) Completed!"

  Upload_script:
      - cd ~/znxt/ccache
      - ls -lh
      - ./ziping.sh
      - ls -lh
      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Uploading ccache...."
      - rclone copy ccache.tar.gz znxt:ccache -P
      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Uploading ccache Success"
      - cd ~/rom/out/target/product/maple_dsds/obj/KERNEL_OBJ/arch/arm64/boot
      - curl --upload-file Image.gz-dtb https://transfer.sh/Image.gz-dtb
      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Uploading Build $(cd ~/rom/out/target/product/maple_dsds/out/target/product/maple_dsds/ && ls *.zip)"
      - cd ~/rom/out/target/product/maple_dsds
      - ls -lh
      - pwd
      - chmod 777 *
      - curl --upload-file *.zip https://transfer.sh/$(ls *.zip)
      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Build $(ls *.zip) Uploaded Successfully!"
      - cat link.txt && echo " "
  
