env:
    rcloneconfig: "ENCRYPTED[32b6ff68080e9be8c9324bc134955912eb5b784a3eb285433315c42a66be5afe1759c3eb1e182c32db213d86025bc58a]"
    TG_TOKEN: "ENCRYPTED[7888fd688129c58fcd9a25086dad02a0c103986cfca92f0d1606b3873ab2e02fffacffe4a8a432b0d726eff81999323e]"
    TG_CHAT_ID: "ENCRYPTED[e06537f430d3e1dfd6bd23c324f9f5d0ac0a67807e496b194aa1a1bfb4c4a8aae6b6eb77bdcb5ae2f043b9b09cc00bc5]"
    LUNCH: lineage_maple_dsds-userdebug
    MAKE: make bacon
 
task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m  
  container:
      image: ghcr.io/iamshubh69/docker:main
      cpu: 8
      memory: 32G
  
  Sync_script:
      - echo "============================"
      - echo "Menyinkronkan Sumber..."
      - echo "============================"
      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Mulai sinkronisasi Sumber..."
      - cd ~
      - mkdir rom
      - cd rom
      - git clone --depth=1 https://github.com/ariffjenong/android_device_sony_maple_dsds -b Lineage-18.1 device/sony/maple_dsds
      - git clone --depth=1 https://github.com/ariffjenong/android_device_sony_yoshino-common -b lineage-18.1 device/sony/yoshino-common
      - git clone --depth=1 https://github.com/ariffjenong/android_vendor_sony_maple_dsds -b lineage-18.1 vendor/sony/maple_dsds
      - git clone --depth=1 https://github.com/ariffjenong/android_kernel_sony_msm8998 -b Lineage-18.1 kernel/sony/maple_dsds
      - repo init -u https://github.com/LineageOS/android.git -b lineage-18.1
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
       - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Sinkronisasi Selesai!"
      - echo "============================"
      - echo "Sinkronisasi Selesai!"
      - echo "============================"

  Build_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
      - export ALLOW_MISSING_DEPENDENCIES=true
      - cd ~
      - cd rom
      - export BUILD_BROKEN_DUP_RULES=true
      - export USE_CCACHE=1 >> ~/.bashrc
      - ccache -M 40G
      - . build/envsetup.sh
      - lunch lineage_maple_dsds-userdebug
      - make -j8 bacon
      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Build $(cd /tmp/rom/out/target/product/juice/ && ls lineage*.zip) Completed!"
      - echo "============================"
      - echo "Build Completed!"
      - echo "============================"

  Upload_script:
      - echo "============================"
      - echo "Mengunggah Build...."
      - echo "============================"
      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Uploading Build $(cd /tmp/rom/out/target/product/juice/ && ls lineage*.zip)"
      - cd ~
      - cd rom
      - cd out/target/product/maple_dsds
      - ls -lh
      - pwd
      - chmod 777 *
      - curl --upload-file V*.zip https://transfer.sh
      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Build $(cd /tmp/rom/out/target/product/juice/ && ls *.zip) Uploaded Successfully!"
      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Download link https://cloud.mobxs.workers.dev/juice/$(cd /tmp/rom/out/target/product/juice/ && ls lineage*.zip)"
      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Compres ccache"
#      - ./ziping.sh
#      - cd /tmp
      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Uploading ccache...."
#      - rclone copy ccache.tar.gz znxt:lineage -P
      - echo " "
      - echo "============================"
      - echo "Build Berhasil Diunggah!"
      - echo "============================"
  
