env:
    rclone_config: "ENCRYPTED[4922bc14514c7f61d60c12b9e1f9bf4d93bd95dc0ea4f51a5569580948e8404a427dd178aa07413e6fbd784459a0c828]"
    TG_TOKEN: "ENCRYPTED[7888fd688129c58fcd9a25086dad02a0c103986cfca92f0d1606b3873ab2e02fffacffe4a8a432b0d726eff81999323e]"
    TG_CHAT_ID: "ENCRYPTED[e06537f430d3e1dfd6bd23c324f9f5d0ac0a67807e496b194aa1a1bfb4c4a8aae6b6eb77bdcb5ae2f043b9b09cc00bc5]"
    SF_USERNAME: "ENCRYPTED[9b9deac88b090b7dc4e69a058e79360e8832c782b9bd46499a7f1401e66e219bad7c9c901a85eeb0d154f717cfc5f148]"
    SF_PASS: "ENCRYPTED[9d4e6509f1294d4d9b39c9f092f32123bef7cdf2c773cda6f80867a329c629d6ab9f1cee0db0c38184bd13d8e8a5556f]"
    GIT: "ENCRYPTED[88a0e7d9ccae8b857e92f99c29c578f7b16db76651470719eb17ed0bb8e79fb3e4062cb9dab6dbccde1e62a8c5e2b97e]"
    ROM_PROJECT: "nusantara-12"
 
task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 1h  
  container:
      image: inok2341/anu:latest
      cpu: 4
      memory: 8G

  Download_script:
      - cd ~
      - git config --global user.name "ariffjenong"
      - git config --global user.email "arifbuditantodablekk@gmail.com"
      - git config --global user.name
      - git config --global user.email
      - mkdir -p ~/.config/rclone
      #- echo "$rclone_config" > ~/.config/rclone/rclone.conf
      - mkdir -p ~/rom
      - cd ~/rom
      - git clone https://github.com/NusantaraProject-ROM/android_frameworks_base.git -b 12 android_frameworks_base
      - cd android_frameworks_base
      - git remote add pro https://$GIT/ariffjenong/android_frameworks_base.git
      - git push -u pro 12

  SF_script:
      #- ./sf.sh
      - ./build_zip.sh
      #- cd ~/rom/out/target/product/maple_dsds
      #- rclone copy $(ls *.zip) znxtproject:rom/$ROM_PROJECT
      - cd ~ && rm -rf rom
 