env:
    rclone_config: "ENCRYPTED[4922bc14514c7f61d60c12b9e1f9bf4d93bd95dc0ea4f51a5569580948e8404a427dd178aa07413e6fbd784459a0c828]"
    TG_TOKEN: "ENCRYPTED[7888fd688129c58fcd9a25086dad02a0c103986cfca92f0d1606b3873ab2e02fffacffe4a8a432b0d726eff81999323e]"
    TG_CHAT_ID: "ENCRYPTED[e06537f430d3e1dfd6bd23c324f9f5d0ac0a67807e496b194aa1a1bfb4c4a8aae6b6eb77bdcb5ae2f043b9b09cc00bc5]"
 
task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 4h  
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G

  Env_script:
      - cd ~
      - mkdir -p ~/rom
      - mkdir -p ~/znxt
      - mkdir -p ~/.config/rclone
      - echo "$rclone_config" > ~/.config/rclone/rclone.conf
      - time rclone copy znxt:ccache/nad12/ccache.tar.gz ~/znxt -P
      - cd ~/znxt
      - time tar xf ccache.tar.gz
      - rm -rf ccache.tar.gz
      - cd ~/znxt/ccache
      - ls -lh

  Sync_script:
      - cd ~/rom
      - repo init --depth=1 --no-repo-verify -u https://github.com/NusantaraProject-ROM/android_manifest.git -b 12 -g default,-mips,-darwin,-notdefault
      - git clone https://github.com/ariffjenong/local_manifest.git --depth 1 -b nad-12 .repo/local_manifests
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
 #     - grep -R 'allow system_server root_block_device:blk_file'
#      - grep -R 'allow system_server xbl_block_device:blk_file'
#      - grep -R 'allow system_server gpt_block_device:blk_file'

  Build_script:
      - ./build.sh

  Upload_file_script:
      - ./build_zip.sh
#      - rom_output=~/rom/out/target/product/maple_dsds/*.zip
#      - curl -F document=@$rom_output https://api.telegram.org/TG_TOKEN/sendDocument?chat_id=TG_CHAT_ID &&  cd ~/rom/out/target/product/maple_dsds
 #     - ls -lh
  #    - cd ~/znxt/ccache
  #    - ls -lh
      - cd ~/rom/out/target/product/maple_dsds
      - ls -lh
      - pwd
#      - chmod 777 *
#      - curl --upload-file *.zip https://transfer.sh/$(ls *.zip)
   #   - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Build $(ls *.zip) Uploaded Successfully!"
     # - cat link.txt && echo " "
  
