env:
    rcloneconfig: "ENCRYPTED[32b6ff68080e9be8c9324bc134955912eb5b784a3eb285433315c42a66be5afe1759c3eb1e182c32db213d86025bc58a]"
    TG_TOKEN: "ENCRYPTED[7888fd688129c58fcd9a25086dad02a0c103986cfca92f0d1606b3873ab2e02fffacffe4a8a432b0d726eff81999323e]"
    TG_CHAT_ID: "ENCRYPTED[e06537f430d3e1dfd6bd23c324f9f5d0ac0a67807e496b194aa1a1bfb4c4a8aae6b6eb77bdcb5ae2f043b9b09cc00bc5]"
    LUNCH: bliss_maple_dsds-userdebug
    MAKE: make bacon
 
task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m  
  container:
      image: ghcr.io/iamshubh69/docker:main
      cpu: 8
      memory: 32G
  
  Sync_script:
      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Build baru terdeteksi!"
      - echo "============================"
      - echo "Menyinkronkan Sumber..."
      - echo "============================"
      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Mulai sinkronisasi Sumber..."
      - cd ~
      - mkdir rom
      - cd rom
      - git clone --depth=1 https://github.com/ariffjenong/android_device_sony_maple_dsds -b S device/sony/maple_dsds
      - git clone --depth=1 https://github.com/ariffjenong/android_device_sony_yoshino-common -b S device/sony/yoshino-common
      - git clone --depth=1 https://github.com/ariffjenong/android_vendor_sony_maple_dsds --single-branch -b S vendor/sony/maple_dsds
      - git clone --depth=1 https://github.com/ariffjenong/android_kernel_sony_msm8998 -b lineage-19.0_bpf_backport kernel/sony/msm8998
      - git clone --depth=1 https://github.com/kdrag0n/proton-clang -b master prebuilts/clang/host/linux-x86/clang-proton
      - repo init -u https://github.com/BlissRoms/platform_manifest.git -b arcadia
      - repo sync -c --force-sync --no-tags --no-clone-bundle -j$(nproc --all) --optimized-fetch --prune

  Build_script:
      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Sinkronisasi Selesai!"
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Mulai Membangun BLISS ROM"
      - export ALLOW_MISSING_DEPENDENCIES=true
      - export DEBIAN_FRONTEND=noninteractive
      - export SELINUX_IGNORE_NEVERALLOW=true
      - export CC=clang
      - export CLANG_TRIPLE=aarch64-linux-gnu-
      - export CROSS_COMPILE=aarch64-linux-gnu-
      - export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
      - DEBIAN_FRONTEND=noninteractive
      - sudo python setup.py clean
      - sudo python3 setup.py install
      - git submodule sync
      - git submodule deinit -f .
      - git submodule update --init --recursive
      - git config --global user.name "ariffjenong"
      - git config --global user.email "arifbuditantodablekk@gmail.com"
      - cd ~
      - cd rom
      - export BUILD_BROKEN_DUP_RULES=true
      - export USE_CCACHE=1 >> ~/.bashrc
      - ccache -M 40G
      - . build/envsetup.sh
      - blissify -v bliss_maple_dsds-userdebug

  Upload_script:
      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Build $(cd /tmp/rom/out/target/product/maple_dsds/ && ls *.zip) Completed!"
      - echo "============================"
      - echo "Build Completed!"
      - echo "============================"
      - echo "============================"
      - echo "Mengunggah Build...."
      - echo "============================"
#      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Uploading Build $(cd /tmp/rom/out/target/product/maple_dsds/ && ls *.zip)"
      - cd ~
      - cd rom
      - cd out/target/product/maple_dsds
      - ls -lh
      - pwd
      - chmod 777 *
      - curl --upload-file *.zip https://transfer.sh
#      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Build $(cd /tmp/rom/out/target/product/maple_dsds/ && ls *.zip) Uploaded Successfully!"
#      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Download link https://cloud.mobxs.workers.dev/maple_dsds/$(cd /tmp/rom/out/target/product/maple_dsds/ && ls *.zip)"
#      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Compres ccache"
#      - ./ziping.sh
#      - cd /tmp
#      - curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Uploading ccache...."
#      - rclone copy ccache.tar.gz znxt:lineage -P
      - echo " "
      - echo "============================"
      - echo "Build Berhasil Diunggah!"
      - echo "============================"
      - echo "----------------------------"
      - cat link.txt && echo " "
      - echo "============================"
 
