env:
    rclone_config: "ENCRYPTED[3c83ff4e129f1ced7d697b973f99d3cf33fd7936b9ad27602c7ffa47c5d678da1c8cc1fcf2ab067b09fe35e501b6ad75]"
    TG_TOKEN: "ENCRYPTED[7888fd688129c58fcd9a25086dad02a0c103986cfca92f0d1606b3873ab2e02fffacffe4a8a432b0d726eff81999323e]"
    TG_CHAT_ID: "ENCRYPTED[e06537f430d3e1dfd6bd23c324f9f5d0ac0a67807e496b194aa1a1bfb4c4a8aae6b6eb77bdcb5ae2f043b9b09cc00bc5]"
    SF_USERNAME: "ENCRYPTED[9b9deac88b090b7dc4e69a058e79360e8832c782b9bd46499a7f1401e66e219bad7c9c901a85eeb0d154f717cfc5f148]"
    SF_PASS: "ENCRYPTED[9d4e6509f1294d4d9b39c9f092f32123bef7cdf2c773cda6f80867a329c629d6ab9f1cee0db0c38184bd13d8e8a5556f]"
    ROM_PROJECT: "Bliss"
 
task:
  name: Syncing, Building and Uploading
  timeout_in: 4h  
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G

  Env_script:
      - cd ~
      - rm -rf ~/rom
      - rm -rf ~/znxt
      - mkdir -p ~/rom
      - mkdir -p ~/znxt
      - mkdir -p ~/.config/rclone
      - echo "$rclone_config" > ~/.config/rclone/rclone.conf
      - time rclone copy znxtproject:ccache/$ROM_PROJECT/ccache.tar.gz ~/znxt -P
      - cd ~/znxt
      - time tar xf ccache.tar.gz
      - rm ccache.tar.gz

  Sync_script:
      - cd ~/rom
      - repo init --depth=1 --no-repo-verify -u git://github.com/BlissRoms/platform_manifest.git -b arcadia -g default,-mips,-darwin,-notdefault
      - git clone https://github.com/ariffjenong/local_manifest.git --depth=1 -b $ROM_PROJECT .repo/local_manifests
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j24 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j12

  Build_script:
      - ./build.sh

  Upload_script:
      #- ./build_zip.sh
      #- cd ~/rom/out/target/product/maple_dsds/obj/KERNEL_OBJ/arch/arm64/boot/
      #- rclone copy Image.gz-dtb znxtproject:kernel12 -P
      #- ls -lh
      - cd ~/rom/out/target/product/maple_dsds
      - ls -lh
      - product=$(ls *maple_dsds*UNOFFICIAL*.zip)
      - md5sum=$(ls *.md5sum)
      - rclone copy $product znxtproject:rom/bliss-12 -P
      - rclone copy $md5sum znxtproject:rom/bliss-12 -P

  SF_script:
      #- ./sf.sh
      #- curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Build $(cd ~/rom/out/target/product/maple_dsds && ls *UNOFFICIAL*.zip) Uploaded Successfully!"
      - cd ~ && rm -rf rom && rm -rf znxt
  