env:
    rclone_config: "ENCRYPTED[3c83ff4e129f1ced7d697b973f99d3cf33fd7936b9ad27602c7ffa47c5d678da1c8cc1fcf2ab067b09fe35e501b6ad75]"
    TG_TOKEN: "ENCRYPTED[7888fd688129c58fcd9a25086dad02a0c103986cfca92f0d1606b3873ab2e02fffacffe4a8a432b0d726eff81999323e]"
    TG_CHAT_ID: "ENCRYPTED[e06537f430d3e1dfd6bd23c324f9f5d0ac0a67807e496b194aa1a1bfb4c4a8aae6b6eb77bdcb5ae2f043b9b09cc00bc5]"
    SF_USERNAME: "ENCRYPTED[9b9deac88b090b7dc4e69a058e79360e8832c782b9bd46499a7f1401e66e219bad7c9c901a85eeb0d154f717cfc5f148]"
    SF_PASS: "ENCRYPTED[9d4e6509f1294d4d9b39c9f092f32123bef7cdf2c773cda6f80867a329c629d6ab9f1cee0db0c38184bd13d8e8a5556f]"
    ROM_PROJECT: "nusantara-12"
 
task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 1h  
  container:
      image: inok2341/anu:latest
      cpu: 4
      memory: 8G

  Download_script:
      - cd ~
      - mkdir -p ~/rom/out/target/product/maple_dsds
      - cd ~/rom/out/target/product/maple_dsds
      - time aria2c https://roms.cirrus-ci.workers.dev/0:/maple_dsds/Nusantara_v4.0-1-12-maple_dsds-Gapps-01032022-UNOFFICIAL-0232.zip -x16 -s50
      - time aria2c https://roms.cirrus-ci.workers.dev/0:/maple_dsds/Nusantara_v4.0-1-12-maple_dsds-02032022-UNOFFICIAL-0719.zip -x16 -s50
      - sudo apt-get update -y && sudo apt-get install unzip -y && sudo apt-get install zip -y
      - gap=$(ls *Gapps*.zip)
      - time unzip $gap -d Nusantara_v4.0-1-12-maple_dsds-Gapps-01032022-UNOFFICIAL-0232
      - rm $gap
      - van=$(ls *maple_dsds*.zip)
      - time unzip $van -d Nusantara_v4.0-1-12-maple_dsds-02032022-UNOFFICIAL-0719
      - rm $van
      - cd Nusantara_v4.0-1-12-maple_dsds-Gapps-01032022-UNOFFICIAL-0232
      - rm boot.img && cd ..
      - cd Nusantara_v4.0-1-12-maple_dsds-02032022-UNOFFICIAL-0719
      - mv boot.img ~/rom/out/target/product/maple_dsds/Nusantara_v4.0-1-12-maple_dsds-Gapps-01032022-UNOFFICIAL-0232/
      - cd ~/rom/out/target/product/maple_dsds
      - rm -rf Nusantara_v4.0-1-12-maple_dsds-02032022-UNOFFICIAL-0719
      - name=Nusantara_v4.0-1-12-maple_dsds-Gapps-01032022-UNOFFICIAL-0232
      - time zip -r $name $name.zip
      - rm -rf $name
      

  SF_script:
      #- ./sf.sh
      - cd ~/rom/out/target/product/maple_dsds
      - time rclone copy $(ls Nusantara*.zip) znxtproject:rom/nusantara
